env:
  browser: true
  jest: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ['error', 4],
  import/extensions: 'off',
  import/prefer-default-export: 'off',
  no-plusplus: 'off'
}
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
