service: wannamusic-bot
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
functions:
  wannamusic-bot:
    handler: ./func/webhook.handler
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    events:
      - http:
          path: wannamusic-bot
          method: post
          cors: true
  wannamusic-send-document:
    handler: ./func/send-document.handler
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      S3_BUCKET: ${env:S3_BUCKET}
    events:
      - s3:
        bucket: ${env:S3_BUCKET}
        event: s3:ObjectCreated:*
        existing: true
